rentACar/mdapi/objects/Car__c.object
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Available_For_Rent__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Available For Rent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Car_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Car Type</label>
        <referenceTo>Car_Type__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Per_Day_Rent__c</fullName>
        <description>Per day rent of the car</description>
        <label>Per Day Rent</label>
        <precision>7</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
</CustomObject>

rentACar/mdapi/objects/Car_Type__c.object
<CustomObject>
    <description>Property object to store different car type</description>
    <label>Car Type</label>
    <nameField>
        <label>Car Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

rentACar/force-app/main/default/classes/getCarTypeIdResults.cls
public with sharing class getCarTypeIdResults {
   
    @AuraEnabled(cacheable=TRUE)
    public static List<Car__c> getResults(String ctId){
        System.debug(ctId);
            if(String.isEmpty(ctId)){

                return [select Name, Car_Type__c, Contact__c,Picture__c, Per_Day_Rent__c,
                        Geolocation__latitude__s, Geolocation__longitude__s
                        FROM Car__c 
                        WHERE Available_For_Rent__c=TRUE ];
                
    
            }else{
                return  [select Name, Car_Type__c, Contact__c,Picture__c, Per_Day_Rent__c,
                        Geolocation__latitude__s, Geolocation__longitude__s
                        FROM Car__c 
                        WHERE Available_For_Rent__c=TRUE AND
                        Car_Type__c =: ctId];
    
                        
            }
        
}
}